// app/[tenant]/page.tsx
export default async function TenantPage({
  params,
}: {
  params: Promise<{ tenant: string }>;
}) {
  const { tenant } = await params;
  
  return (
    <div style={{ padding: '2rem', fontFamily: 'sans-serif' }}>
      <h1>Welcome to the portal for: {tenant}</h1>
      <p>This page is dynamically generated by the multi-tenant CMS system.</p>
    </div>
  );
}
